var a = {
    _id: { $oid: "5ed21de5d036465c4ed58d2a" },
    name: "重庆三峡融资担保集团股份有限公司",
    "电话：": "023-6356****",
    "邮箱：": "cqsxdb@cqsxdb.com",
    "官网：": "www.cqsxdb.com",
    "地址：": "重庆市渝北区青枫北路12号3幢",
    "简介：":
        "重庆三峡融资担保集团股份有限公司成立于2006年04月30日，注册地位于重庆市渝北区青枫北路12号3幢，法定代表人为李卫东。经营范围包...展开",
    注册资本: "465,000万(元)",
    实缴资本: "-",
    法定代表人: "李卫东",
    经营状态: "开业",
    曾用名: "-",
    所属行业: "货币金融服务",
    统一社会信用代码: "91500000787481580L",
    纳税人识别号: "91500000787481580L",
    工商注册号: "500000000004479",
    组织机构代码: "78748158-0",
    登记机关: "重庆市工商行政管理局",
    成立日期: "2006-04-30",
    企业类型: "股份有限公司",
    营业期限: "2006-04-30 至 无固定期限",
    行政区划: "重庆市渝北区",
    "审核/年检日期": "2018-06-08",
    注册地址: "重庆市渝北区青枫北路12号3幢查看地图",
    经营范围:
        "贷款担保、票据承兑担保、贸易融资担保、项目融资担保、信用证担保等融资性担保业务；再担保，债券发行担保（按许可证核定期限从事经营）。 诉...  展开",
    persons: [
        { person_name: "李卫东", person_job: "董事长" },
        { person_name: "曾志伟", person_job: "董事" },
        { person_name: "曾志远", person_job: "董事" },
        { person_name: "陈立宏", person_job: "董事" },
        { person_name: "王桂萍", person_job: "董事" },
        { person_name: "王洋", person_job: "董事" },
        { person_name: "于莫", person_job: "董事" },
        { person_name: "曹晓明", person_job: "监事会主席" },
        { person_name: "聂晓威", person_job: "监事" },
        { person_name: "邹伟", person_job: "监事" },
    ],
    invests: [
        {
            invest_name: "重庆两江新区长江三峡小额贷款有限公司",
            invest_ratio: "50%",
            renjiao_amount: "25,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆泽晖股权投资基金管理有限公司",
            invest_ratio: "70%",
            renjiao_amount: "700万(元)",
            status: "开业",
        },
        {
            invest_name: "湖北长江兴宁新兴产业投资基金合伙企业(有限合伙)",
            invest_ratio: "-",
            renjiao_amount: "-",
            status: "开业",
        },
        {
            invest_name: "重庆渝台融资担保有限公司",
            invest_ratio: "-",
            renjiao_amount: "-",
            status: "开业",
        },
        {
            invest_name: "重庆中新叁号股权投资中心(有限合伙)",
            invest_ratio: "-",
            renjiao_amount: "-",
            status: "开业",
        },
        {
            invest_name: "重庆市鸿业融资担保有限责任公司",
            invest_ratio: "4.17%",
            renjiao_amount: "1,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆金宝保信息技术服务有限公司",
            invest_ratio: "51%",
            renjiao_amount: "1,530万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆市再担保有限责任公司",
            invest_ratio: "5%",
            renjiao_amount: "5,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆市教育融资担保有限公司",
            invest_ratio: "-",
            renjiao_amount: "12,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆市铭禹电力有限公司",
            invest_ratio: "100%",
            renjiao_amount: "2,000万(元)",
            status: "开业",
        },
    ],
    holders: [
        {
            holder_name: "中国长江三峡集团公司",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "100,000万(元)",
        },
        {
            holder_name: "重庆渝富资产经营管理集团有限公司",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "150,000万(元)",
        },
        {
            holder_name: "国开金融有限责任公司",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "50,000万(元)",
        },
        {
            holder_name: "中国长江三峡集团公司A",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "100,000万(元)",
        },
        {
            holder_name: "重庆渝富资产经营管理集团有限公司A",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "150,000万(元)",
        },
        {
            holder_name: "国开金融有限责任公司A",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "50,000万(元)",
        },
        {
            holder_name: "中国长江三峡集团公司B",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "100,000万(元)",
        },
        {
            holder_name: "重庆渝富资产经营管理集团有限公司B",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "150,000万(元)",
        },
        {
            holder_name: "国开金融有限责任公司B",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "50,000万(元)",
        },
    ],
    controls: [
        { 被控股企业: "重庆市铭禹电力有限公司", 投资占比: "100%" },
        { 被控股企业: "重庆两江新区长江三峡小额贷款有限公司", 投资占比: "53%" },
        { 被控股企业: "重庆市教育融资担保有限公司", 投资占比: "100%" },
    ],
};
var b = {
    _id: { $oid: "5ed21de5d036465c4ed58d31" },
    name: "重庆渝台融资担保有限公司",
    "电话：": "6564****",
    "邮箱：": "yutaidanbao@xinlang.com",
    "官网：": "www.yutaidb.com",
    "地址：": "重庆市沙坪坝区西永微电子产业园软件研发楼B1 3层",
    "简介：":
        "重庆渝台融资担保有限公司成立于2009年05月11日，注册地位于重庆市沙坪坝区西永微电子产业园软件研发楼B1 3层，法定代表人为张永红...展开",
    注册资本: "30,000万(元)",
    实缴资本: "-",
    法定代表人: "张永红",
    经营状态: "开业",
    曾用名: "-",
    所属行业: "货币金融服务",
    统一社会信用代码: "91500000688915099K",
    纳税人识别号: "91500000688915099K",
    工商注册号: "500000000001597",
    组织机构代码: "68891509-9",
    登记机关: "重庆市市场监督管理局",
    成立日期: "2009-05-11",
    企业类型: "有限责任公司",
    营业期限: "2009-05-11 至 无固定期限",
    行政区划: "重庆市沙坪坝区",
    "审核/年检日期": "2018-05-21",
    注册地址: "重庆市沙坪坝区西永微电子产业园软件研发楼B1 3层查看地图",
    经营范围:
        "贷款担保、票据承兑担保、贸易融资担保、项目融资担保、信用证担保等融资性担保业务；诉讼保全担保业务，履约担保业务，与担保业务有关的融资咨...  展开",
    persons: [
        { person_name: "张永红", person_job: "董事长" },
        { person_name: "邓夔", person_job: "总经理" },
        { person_name: "郭朝林", person_job: "董事" },
        { person_name: "孙策兵", person_job: "董事" },
        { person_name: "周黎祥", person_job: "董事" },
        { person_name: "周云霞", person_job: "董事" },
        { person_name: "丁瑞", person_job: "监事会主席" },
        { person_name: "韩韪峰", person_job: "监事" },
        { person_name: "何亚飞", person_job: "监事" },
        { person_name: "张伟峰", person_job: "监事" },
    ],
    invests: [
        {
            invest_name: "重庆两江新区长江三峡小额贷款有限公司",
            invest_ratio: "2%",
            renjiao_amount: "1,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆两江新区长江三峡小额贷款有限公司a",
            invest_ratio: "2%",
            renjiao_amount: "1,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆两江新区长江三峡小额贷款有限公司b",
            invest_ratio: "2%",
            renjiao_amount: "1,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆两江新区长江三峡小额贷款有限公司c",
            invest_ratio: "2%",
            renjiao_amount: "1,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆两江新区长江三峡小额贷款有限公司d",
            invest_ratio: "2%",
            renjiao_amount: "1,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆两江新区长江三峡小额贷款有限公司e",
            invest_ratio: "2%",
            renjiao_amount: "1,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆两江新区长江三峡小额贷款有限公司f",
            invest_ratio: "2%",
            renjiao_amount: "1,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆两江新区长江三峡小额贷款有限公司g",
            invest_ratio: "2%",
            renjiao_amount: "1,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆两江新区长江三峡小额贷款有限公司h",
            invest_ratio: "2%",
            renjiao_amount: "1,000万(元)",
            status: "开业",
        },
        {
            invest_name: "重庆两江新区长江三峡小额贷款有限公司i",
            invest_ratio: "2%",
            renjiao_amount: "1,000万(元)",
            status: "开业",
        },
    ],
    holders: [
        {
            holder_name: "重庆三峡担保集团股份有限公司",
            holder_ratio: "-",
            renjiao_amount: "20,000万(元)",
            actual_amount: "20,000万(元)",
        },
        {
            holder_name: "重庆瑞诚创业投资担保有限公司",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "5,000万(元)",
        },
        {
            holder_name: "重庆西永微电子产业园区开发有限公司",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "5,000万(元)",
        },
    ],
};
var c = {
    _id: { $oid: "5ed21de5d036465c4ed58d31" },
    name: "中国长江三峡集团公司",
    "电话：": "6564****",
    "邮箱：": "yutaidanbao@xinlang.com",
    "官网：": "www.yutaidb.com",
    "地址：": "重庆市沙坪坝区西永微电子产业园软件研发楼B1 3层",
    "简介：":
        "重庆渝台融资担保有限公司成立于2009年05月11日，注册地位于重庆市沙坪坝区西永微电子产业园软件研发楼B1 3层，法定代表人为张永红...展开",
    注册资本: "30,000万(元)",
    实缴资本: "-",
    法定代表人: "张永红",
    经营状态: "开业",
    曾用名: "-",
    所属行业: "货币金融服务",
    统一社会信用代码: "91500000688915099K",
    纳税人识别号: "91500000688915099K",
    工商注册号: "500000000001597",
    组织机构代码: "68891509-9",
    登记机关: "重庆市市场监督管理局",
    成立日期: "2009-05-11",
    企业类型: "有限责任公司",
    营业期限: "2009-05-11 至 无固定期限",
    行政区划: "重庆市沙坪坝区",
    "审核/年检日期": "2018-05-21",
    注册地址: "重庆市沙坪坝区西永微电子产业园软件研发楼B1 3层查看地图",
    经营范围:
        "贷款担保、票据承兑担保、贸易融资担保、项目融资担保、信用证担保等融资性担保业务；诉讼保全担保业务，履约担保业务，与担保业务有关的融资咨...  展开",
    persons: [
        { person_name: "张永红", person_job: "董事长" },
        { person_name: "邓夔", person_job: "总经理" },
        { person_name: "郭朝林", person_job: "董事" },
        { person_name: "孙策兵", person_job: "董事" },
        { person_name: "周黎祥", person_job: "董事" },
        { person_name: "周云霞", person_job: "董事" },
        { person_name: "丁瑞", person_job: "监事会主席" },
        { person_name: "韩韪峰", person_job: "监事" },
        { person_name: "何亚飞", person_job: "监事" },
        { person_name: "张伟峰", person_job: "监事" },
    ],
    invests: [],
    holders: [
        {
            holder_name: "重庆三峡担保集团股份有限",
            holder_ratio: "-",
            renjiao_amount: "20,000万(元)",
            actual_amount: "20,000万(元)",
        },
        {
            holder_name: "重庆瑞诚创业投资担保有限",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "5,000万(元)",
        },
        {
            holder_name: "重庆西永微电子产业园区开发有限",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "5,000万(元)",
        },
        {
            holder_name: "重庆三峡担保集团股份有限a",
            holder_ratio: "-",
            renjiao_amount: "20,000万(元)",
            actual_amount: "20,000万(元)",
        },
        {
            holder_name: "重庆瑞诚创业投资担保有限a",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "5,000万(元)",
        },
        {
            holder_name: "重庆西永微电子产业园区开发有限a",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "5,000万(元)",
        },
        {
            holder_name: "重庆三峡担保集团股份有限b",
            holder_ratio: "-",
            renjiao_amount: "20,000万(元)",
            actual_amount: "20,000万(元)",
        },
        {
            holder_name: "重庆瑞诚创业投资担保有限b",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "5,000万(元)",
        },
        {
            holder_name: "重庆西永微电子产业园区开发有限b",
            holder_ratio: "-",
            renjiao_amount: "-",
            actual_amount: "5,000万(元)",
        },
    ],
};

var arr = [];
function mock(obj) {
    for (let i = 0; i < 20; i++) {
        arr.push({
            ...obj,
            holders: obj.holders.map((h) => ({ ...h, holder_name: h.holder_name + i })),
            invests: obj.invests.map((h) => ({ ...h, invest_name: h.invest_name + i })),
        });
    }
}

mock(a);
mock(b);
mock(c);

console.log(arr.map((a) => JSON.stringify(a)).join("\n"));
